language: generic
sudo: false

branches:
  only:
    - master
    - /^\d+\.\d+.*$/

os:
  - linux

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - $HOME/miniconda/bin/conda install conda conda-build conda-verify anaconda-client --yes
  - source $HOME/miniconda/bin/activate
  - conda info -a

script:
  - conda build conda-recipe
