name: default
dependencies:
- python=2.7
- bokeh
- cvxopt
- ipykernel
- matplotlib
- pandas
- pip
- psutil
- python
- r-base=3.5.1
- r-ggplot2
- r-irkernel
- r-yaml
- statsmodels
- toolz
# Not requested, but pull in some extras for testing
- nomkl
- jupyter
- r-essentials
- pip:
  - ruamel.yaml

